[tool.poetry]
name = "yautils"
version = "0.1.0"
description = ""
authors = ["Chen Yang <chen.yang@gm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
loguru = "^0.7.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
